volumes:
  postgresql_data:

networks:
  wiyatago:
    driver: bridge

services:
  postgresql:
    image: docker.io/library/postgres:${DB_VERSION}
    container_name: wiyatago-postgresql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql
    networks:
      - wiyatago